SELECT TOP (1000) [bookID]
      ,[bookTitle]
      ,[bookPrice]
      ,[bookDescription]
      ,[bookImage1]
      ,[bookImage2]
      ,[bookImage3]
      ,[dateOfPublisher]
      ,[pageOfNumber]
      ,[inventoryNumber]
      ,[publisherID]
      ,[categoryID]
      ,[ownerID]
  FROM [MainBookManagement].[dbo].[tblBooks]
