SELECT TOP (1000) [customerID]
      ,[customerEmail]
      ,[customerName]
      ,[customerAddress]
      ,[customerPassword]
      ,[customerPhone]
  FROM [MainBookManagement].[dbo].[tblCustomer]
